### ISSUE TITLE
Check settings of AP config script

### ISSUE THREAD

**Issue by vueltaconicarus** [eskimor/gm-it#2]
Looks like the script sets some wrong settings lately (i.e., today):

1. WAN Connection Type was "Disabled", should be "Automatic configuration - DHCP"
2. Network Setup - Router IP: "Gateway" and "Local DNS" were set to 10.134.0.1, should be 0.0.0.0
3. Network Address Server Settings (DHCP): "Use DNSMasq for DNS" and "DHCP-Authoritative" should be "enabled"
4. Network Address Server Settings (DHCP): "Static DNS server" 1 and 2 should be 0.0.0.0

Is it possible that some Router settings get applied to simple APs?

**Comment by eskimor** [comment]
There are no router settings yet in the script ... so no :-)

**Comment by vueltaconicarus** [comment]
Explanation of the mystery: the script does NOT set all settings. Instead, it assumes that the router is in factory settings, and only changes specific settings. The settings mentioned in the initial post were altered while playing around manually, and were not overwritten by the script.

Two possible remedies: 
1) automatically perform a factory reset before specific settings.
2) incorporate all factory settings in the script, to have a full declaration.

We'll go for option 2.

**Comment by vueltaconicarus** [comment]
See last comment.
